# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialApp
pod 'Alamofire', '~> 5.2'
pod 'Swinject'
pod 'RealmSwift'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'

end
